function [A_conv,b_conv] = get_conv_constraint(in1)
%GET_CONV_CONSTRAINT
%    [A_CONV,B_CONV] = GET_CONV_CONSTRAINT(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    07-Jun-2022 20:00:45

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = -x2;
t3 = -x3;
t4 = -x4;
t5 = -x5;
t6 = t2+x1;
t7 = t3+x2;
t8 = t4+x3;
t9 = t5+x4;
t10 = 1.0./t6;
t11 = 1.0./t7;
t12 = 1.0./t8;
t13 = 1.0./t9;
t14 = -t11;
t15 = -t12;
A_conv = reshape([-t10,0.0,0.0,t10+t11,t14,0.0,t14,t11+t12,t15,0.0,t15,t12+t13,0.0,0.0,-t13],[3,5]);
if nargout > 1
    b_conv = [0.0;0.0;0.0];
end
